### ISSUE TITLE
Feature request: formal package and entrypoint

### ISSUE THREAD

**Issue by mbeacom** [awslabs/aws-cloudsaga#2]
The current workflow dictates that a user clone this repository and interact with the `cloudsaga.py` directly.

I propose transitioning to a `pyproject.toml` driven workflow using `poetry` to handle virtual environments, package management, and publishing activities (to pypi).  This pyproject.toml will define an entrypoint `cloudsaga.cloudsaga:main` and restructure the repo to conform to a python package layout.

**Comment by hackersifu** [comment]
Merged into 1.0.1 branch. Will be releasing with 1.0.1 release.
